# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'printer_softward.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(435, 430)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMaximumSize(QtCore.QSize(65, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.ip_line = QtWidgets.QLineEdit(Form)
        self.ip_line.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ip_line.setObjectName("ip_line")
        self.horizontalLayout.addWidget(self.ip_line)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.port_lab = QtWidgets.QLabel(Form)
        self.port_lab.setMinimumSize(QtCore.QSize(60, 0))
        self.port_lab.setMaximumSize(QtCore.QSize(60, 16777215))
        self.port_lab.setObjectName("port_lab")
        self.horizontalLayout.addWidget(self.port_lab)
        self.port_line = QtWidgets.QLineEdit(Form)
        self.port_line.setMinimumSize(QtCore.QSize(60, 0))
        self.port_line.setMaximumSize(QtCore.QSize(65, 16777215))
        self.port_line.setObjectName("port_line")
        self.horizontalLayout.addWidget(self.port_line)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.test_lab = QtWidgets.QLabel(Form)
        self.test_lab.setMaximumSize(QtCore.QSize(65, 16777215))
        self.test_lab.setObjectName("test_lab")
        self.horizontalLayout_2.addWidget(self.test_lab)
        self.test_btn = QtWidgets.QPushButton(Form)
        self.test_btn.setMaximumSize(QtCore.QSize(70, 16777215))
        self.test_btn.setObjectName("test_btn")
        self.horizontalLayout_2.addWidget(self.test_btn)
        spacerItem1 = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.load_lab = QtWidgets.QLabel(Form)
        self.load_lab.setMinimumSize(QtCore.QSize(60, 0))
        self.load_lab.setMaximumSize(QtCore.QSize(60, 16777215))
        self.load_lab.setObjectName("load_lab")
        self.horizontalLayout_2.addWidget(self.load_lab)
        self.load_btn = QtWidgets.QPushButton(Form)
        self.load_btn.setMaximumSize(QtCore.QSize(65, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/SIAS_Open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.load_btn.setIcon(icon)
        self.load_btn.setObjectName("load_btn")
        self.horizontalLayout_2.addWidget(self.load_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.start_btn = QtWidgets.QPushButton(Form)
        self.start_btn.setMaximumSize(QtCore.QSize(70, 16777215))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/VectorEditor_StartEdit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start_btn.setIcon(icon1)
        self.start_btn.setObjectName("start_btn")
        self.horizontalLayout_3.addWidget(self.start_btn)
        spacerItem3 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.stop_btn = QtWidgets.QPushButton(Form)
        self.stop_btn.setMaximumSize(QtCore.QSize(70, 16777215))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/VectorEditor_StopEdit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop_btn.setIcon(icon2)
        self.stop_btn.setObjectName("stop_btn")
        self.horizontalLayout_3.addWidget(self.stop_btn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.textEdit = QtWidgets.QPlainTextEdit(Form)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "远程打印机V1.0"))
        self.label.setText(_translate("Form", "目标IP："))
        self.ip_line.setText(_translate("Form", "192.168.1.118"))
        self.port_lab.setText(_translate("Form", "端口号："))
        self.port_line.setText(_translate("Form", "5001"))
        self.test_lab.setText(_translate("Form", "连接测试"))
        self.test_btn.setText(_translate("Form", "测试"))
        self.load_lab.setText(_translate("Form", "加载文件"))
        self.load_btn.setText(_translate("Form", "Load"))
        self.start_btn.setText(_translate("Form", "开始"))
        self.stop_btn.setText(_translate("Form", "取消"))

